export const INITIALIZE_BOARD = 'INITIALIZE_BOARD';
export const RESET_BOARD = 'RESET_BOARD';
export const SET_BOARD_LOADING = 'SET_BOARD_LOADING';
export const SET_IS_BOARD_SET = 'SET_IS_BOARD_SET';
export const SET_IS_CONFIGURING = 'SET_IS_CONFIGURING';

export const SET_CURRENT_GAMES = 'SET_CURRENT_GAMES';
export const TOGGLE_SELECTED_TILE = 'TOGGLE_SELECTED_TILE';
export const COPY_BETSLIP = 'COPY_BETSLIP';
export const SET_ADDING = 'SET_ADDING';
export const SET_REMOVING = 'SET_REMOVING';

export const REMOVE_ROW_FROM_BETSLIP = 'REMOVE_ROW_FROM_BETSLIP';
export const ABLE_TO_SEND = 'ABLE_TO_SEND';
export const ADD_EMPTY_SLIP = 'ADD_EMPTY_SLIP';

export const DISABLE_REMOVE_SLIP_BUTTON = 'DISABLE_REMOVE_SLIP_BUTTON';
export const CHECK_PURCHASABLE = 'CHECK_PURCHASABLE';
export const SET_EDITING_INDEX = 'SET_EDITING_INDEX';
export const PURCHASE_ALL = 'PURCHASE_ALL';

export const DELETE_AND_RESET_ALL = 'DELETE_AND_RESET_ALL';

export const CALCULATE_SLIP_PRICE = 'CALCULATE_SLIP_PRICE';
export const CALCULATE_GRAND_tOTAL = 'CALCULATE_GRAND_tOTAL';
export const CALCULATE_EDIT_INDEX_PRICE = 'CALCULATE_EDIT_INDEX_PRICE';

export const EMPTY_EDITING_SLIP = 'EMPTY_EDITING_SLIP';
export const CHECK_HAS_STARED = 'CHECK_HAS_STARED';

export const GENERATE_SLIP = 'GENERATE_SLIP';
export const TOGGLE_SHOW_HISTORY = 'TOGGLE_SHOW_HISTORY';
export const TOGGLE_SHOWFUNDS = 'TOGGLE_SHOWFUNDS';
export const SET_SHOW_FUNDS = 'SET_SHOW_FUNDS';


export const FETCH_PREDICTIONS_ALL = 'FETCH_PREDICTIONS_ALL';

export const SET_ISPAYING = 'SET_ISPAYING';
export const EXECUTE_PURCHASE = 'EXECUTE_PURCHASE';
export const SET_ISPAID = 'SET_ISPAID';


export const SET_RECEIPT = 'SET_RECEIPT';
export const TOGGLE_SHOW_RECEIPT = 'TOGGLE_SHOW_RECEIPT';

export const SET_FIXTURE_IDS = 'SET_FIXTURE_IDS';
export const SET_GAMEDATE = 'SET_GAMEDATE';
export const SET_ISTOWALLET = 'SET_ISTOWALLET';
export const SET_SLIPS_NULL = 'SET_SLIPS_NULL';


//CONFIG
export const STOP_RESULT_INITIALIZE = 'STOP_RESULT_INITIALIZE';
export const SETUP_WINNERS = 'SETUP_WINNERS';
export const FETCH_RESULTS = 'FETCH_RESULTS';
export const SET_EVENTDATE = 'SET_EVENTDATE';
export const SET_VERSION="SET_VERSION";
export const IS_RESET="IS_RESET";


//login
export const SET_IS_LOGGED_IN = 'SET_IS_LOGGED_IN';
export const SET_LOGGEDIN_USER = 'SET_LOGGEDIN_USER';
export const SET_USERNAME = 'SET_USERNAME';
export const SET_PASSWORD = 'SET_PASSWORD';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_FORGOT_PASSWORD = 'SET_FORGOT_PASSWORD';
export const SET_FUNDS = 'SET_FUNDS';

//RECEIPT

export const TOGGLE_SHOW_RECEIPT_HISTORY = 'TOGGLE_SHOW_RECEIPT_HISTORY';


//BANKS
export const INITIALIZE_ALLOWED_BANKS = 'INITIALIZE_ALLOWED_BANKS';
export const INITIALIZE_SAVED_BANKS = 'INITIALIZE_SAVED_BANKS';
export const RESET_SAVED_BANKS = 'RESET_SAVED_BANKS';













