export const SET_CURRENT_GAMES = 'SET_CURRENT_GAMES';
export const TOGGLE_SELECTED_TILE = 'TOGGLE_SELECTED_TILE';
export const COPY_BETSLIP = 'COPY_BETSLIP';
export const SET_ADDING = 'SET_ADDING';
export const SET_REMOVING = 'SET_REMOVING';

export const REMOVE_ROW_FROM_BETSLIP = 'REMOVE_ROW_FROM_BETSLIP';
export const ABLE_TO_SEND = 'ABLE_TO_SEND';
export const ADD_EMPTY_SLIP = 'ADD_EMPTY_SLIP';

export const DISABLE_REMOVE_SLIP_BUTTON = 'DISABLE_REMOVE_SLIP_BUTTON';
export const CHECK_PURCHASABLE = 'CHECK_PURCHASABLE';
export const SET_EDITING_INDEX = 'SET_EDITING_INDEX';
export const PURCHASE_ALL = 'PURCHASE_ALL';

export const DELETE_AND_RESET_ALL = 'DELETE_AND_RESET_ALL';

export const CALCULATE_SLIP_PRICE = 'CALCULATE_SLIP_PRICE';
export const CALCULAT_GRAND_tOTAL = 'CALCULAT_GRAND_tOTAL';







