export const ABLE_TO_SEND = 'ABLE_TO_SEND';
export const RESET_TEAMS = 'RESET_TEAMS';

export const TOGGLE_SELECTED_TILE = 'TOGGLE_SELECTED_TILE';

export const REMOVE_ROW_FROM_BETSLIP = 'REMOVE_ROW_FROM_BETSLIP';
export const ADD_ROW_TO_BETSLIP = 'ADD_ROW_TO_BETSLIP';
export const SET_ADDING = 'SET_ADDING';





