export const TOGGLE_SELECTED_TILE = 'TOGGLE_SELECTED_TILE';
export const ADD_ROW_TO_BETSLIP = 'ADD_ROW_TO_BETSLIP';
export const SET_ADDING = 'SET_ADDING';

export const REMOVE_ROW_FROM_BETSLIP = 'REMOVE_ROW_FROM_BETSLIP';
export const ABLE_TO_SEND = 'ABLE_TO_SEND';

export const DISABLE_REMOVE_SLIP_BUTTON = 'DISABLE_REMOVE_SLIP_BUTTON';
export const IS_PURCHASABLE = 'IS_PURCHASABLE';
export const DISABLE_ADD_BUTTONS = 'DISABLE_ADD_BUTTONS';





